/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  links: [
    {
      type: 'link',
      label: 'Explore Ecosystem', // The link label
      href: 'https://evmos.org/ecosystem', // The external URL
    },
    {
      type: 'link',
      label: 'Apply For Grant', // The link label
      href: 'https://www.encode.club/evmosgrants', // The external URL
    },
    {
      type: 'link',
      label: 'Follow our Community Calendar', // The link label
      href: 'https://calendar.google.com/calendar/u/0/embed?src=c_grfooiam12n63762eld4ntue48@group.calendar.google.com&ctz=America/Chicago', // The external URL
    }
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
